steps:

  - label: "Reading a secret from an agent environment hook (incorrectly!) :closed_lock_with_key:"
    key: "show-environment-secret"
    command: "echo password: $MY_ENVIRONMENT_SECRET"

  - label: "Reading a secret from an agent environment hook (correctly!) :unlock:"
    key: "show-environment-secret"
    command: "echo password: $(scripts/show-environment-secret.sh)"
